spring:
  application:
    name: Jwt_Practice

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/jwt'
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jwt:
    secret:
      key: 7JWI64WV7ZWY7IS47JqULuuwmOqwkeyKteuLiOuLpC4gSldUIO2GoO2BsCDrsJzquIkg7Jew7Iq17J2EIOychO2VnCBTZWNyZXQgS2V5IOyeheuLiOuLpC4=
    token:
      expiration: 1800000
    refresh:
      token:
        expiration: 1209600000
